//This is the PHP code for the example at http://brian.sheehans.us/Using-php-with-Adobe-Muse/
//Notice that the head and body declarations gave been removed.

<style type="text/css">


.snippetBox h1 {
	font-weight: bold;
	font-size: 1.5em;
}

.snippetBox {
	/*width: 400px;*/
	float: right;
	background-color: #A2A2A2 ;
	padding:13px;
	font-family: "europa",sans-serif;
}

.snippet {
	float: left;
	background-color: #F7DCB5;
	padding:10px;
	width:300px;
	display: block;
	border:7px;
	margin: 10px 20px;
	font-family: Gotham, "Helvetica Neue", Helvetica, Arial, "sans-serif";
}

@media screen max-width: 1042px {
	.snippetBox {
		/*width:85%;*/
	}
}

</style>

<div class="snippetBox">

<h1>Generated by PHP</h1>

<div class="snippet">

	<?php
		echo "<p>Your IP address is " . $_ENV['REMOTE_ADDR'] . "</p>";
	?>

</div>

<div class="snippet">

	<?php
		echo "<p>Your browser is " . $_ENV['HTTP_USER_AGENT'] . "</p>";
	
	?>

</div>

<div class="snippet">

	<?php
		$date=date_create();
		echo"<p>This page was loaded on<br> ";
		echo date_format($date,"l F n, Y g:i:s A");
		echo "</p>";
	
	?>

</div>

<div class="snippet">

	<?php
	
		$count = file_get_contents("count.txt");
		$count = trim($count);
		$count++;
		$c = fopen("counter.txt","w+");
		fwrite($c,$count);
		fclose($c);
		echo "<p>Number of times this page has been loaded: <strong>" . $count . "</strong>.</p><p> Reload to increment the counter.</p>";
	
	?>

</div>



<div class="snippet">
	<?php
		$l1 = rand(1,69);
		$l2 = rand(1,69);
		$l3 = rand(1,69);
		$l4 = rand(1,69);
		$l5 = rand(1,69);
		
		$pb = rand(1,26);

echo "Powerball number generator: <br>";
echo "$l1 $l2 $l3 $l4 $l5 <b>$pb</b>";

?>

</div>

</div>